Establecimiento - Detalle
iesalonsodemadrigal/android-youthcard pull request #74
Opened 2023-02-08 13:52 UTC by MiM14

## Description de la tarea

Visualización del detalle de un establecimiento.

## ¿Cómo se ha implementado?

Se han desarrollado la vista con los datos pedidos en la Issue. Recoger estos datos ha supuesto realizar cambios en toda la estructura de establecimientos, puesto que no se había implementado ninguna manera de obtener un único establecimiento por ID.
> Esta es la razón por la que esta PR es más grande de lo normal.

Por orden, se han implementado:

1. **Domain**

En esta capa he añadido un caso de uso, un método getById al repositorio y  una modificación al modelo, añadiendo phoneNumber.

2. **Data**

Para obtener este detalle desarrollamos dos rutas, una por cada fuente de datos actuando bajo la siguiente lógica. Si existe en local se devuelve este sino va a buscarlo a remoto .
Se han modificado los modelos de api y entity para añadir un phoneNumber y añadidos los métodos necesarios en el Dao y en los ApiEndPoints.

3. **Presentation**

Siguiendo la misma lógica que sigue todo el proyecto en la capa de presentacion se crea un viewModel y un Fragment para detalle.
El viewModel llama al caso de uso que recoge un modelo UiState con un establecimiento, un error o un boolean isLoading. En este caso para el viewModel añado como novedad una variable `currentState`, que recoge el estado actual de la UiState y que utilizare para utilizar los valores del establecimiento fuera de la función `setUpObservers()`. 

En cuanto al Fragment tiene 3 métodos clave para entender su funcionamiento:

- `setUpView()`  -> Prepara la Toolbar y su menú.
> El botóm de share esta a la espera de una url que compartir. La función esta creada y el intent preparado para implementarlo.

- `setUpObservers()` -> Trabaja junto al viewModel y gestiona los posibles estados de la pantalla(carga, error y datos), de esta salen dos funciones `bind()`(pinta los datos en pantalla) y `initMap()`

- `initMap()` -> Es la función que inicializa el mapa. Una vez iniciado un callback llama a `onMapReady()` y pinta el mapa a nuestro gusto, además de detalles como hacerle click, animaciones, etc, que se pueden hacer con él. En caso del click se ha añadido un método al genérico ShareIntent para abrir mapas

## Keywords

- Domain UseCases, Models
- Data:  Room, Retrofit
- Presentation:  ViewModel, Coroutines, Fragment, Menu,  
- Map: Google Maps, Callbacks, Intents

## Screenshots or Video
Lo pedido:

![image](https://user-images.githubusercontent.com/85709107/217572593-2b0e08fb-7051-4ad7-929f-24ebd8e8a23d.png)
Lo realizado:

https://user-images.githubusercontent.com/85709107/217572546-2cbc86a7-2079-4081-ad2b-2316318dc59e.mp4

## Objetivos

2023-02-09 16:25 UTC, RafaX8 submitted a review, later dismissed
Estupendo, veo que cambiaste lo que te mencioné en clase sobre LiveData🚀

2023-02-10 01:00 UTC, josem-perram requested changes
Ismael, revisa los comentarios, sobre todo el tema de que el detalle debería tener su caché independientemente del listado. El listado está usando un EndPoint muy pesado y seguramente tengamos que modificar los modelos.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/app/commons/ShareIntent.kt
> +    fun openMap(url: String) {
esta función puede ser genérica tipo: openUrl que reciba un titulo y una url.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/app/commons/ShareIntent.kt
> +        val chooser = Intent.createChooser(intent, "Launch maps")
donde tienes "Launch maps" iría el título.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/features/establishments/data/EstablishmentsDataRepository.kt
> +                localDataSource.save(listOf(establishmentRemote))
Cuidado aquí. Los establecimientos de detalles deberían tener su propia caché, no tiene nada que ver con la caché obtenida del listado, son cosas diferentes. Tendrías que crearte una nueva tabla (entity) para guardar el detalle. Revisa ofertas y mira como optamos guardarlo.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/features/establishments/data/local/db/EstablishmentsDao.kt
> +    suspend fun getEstablishmentById(establishmentId: Int): EstablishmentsEntity?
Esto debería tener su propia caché y no recoger de otra vista porque no sabemos tiene todos los datos que necesitamos.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/features/establishments/presentation/EstablishmentDetailFragment.kt
> +                skeleton?.showOriginal()
Esto debería estar una vez se compruebe que no ha sido error.

2023-02-10 01:00 UTC, josem-perram commented on app/src/main/java/com/iesam/youthcard/features/establishments/presentation/EstablishmentDetailFragment.kt
> +                    initMap()
Sólo deberíamos inicializar el mapa si el establecimiento es distinto de nulo. Tendrías que meterlo dentro del let.

2023-02-12 18:55 UTC, josem-perram approved these changes
Genial 🚀

2023-02-12 18:59 UTC, merged