Issue69 listado desarrolladores
iesalonsodemadrigal/android-youthcard pull request #79
Opened 2023-02-09 22:44 UTC by OscarAntona

## DESCRIPCION
En esta rama se ha implementado la funcionalidad de mostrar el listado de desarrolladores de 
en fragmento de perfil.
## COMO SE HA IMPLEMENTADO 

VISTAS:
Para ello primeramente he creado las dos vistas necesarias, la que contiene el recycler y la del item.

DATA:
Antes de empezar con dominio y presentacion, he definido todo lo necesario para utilizar retrofit y 
recoger los datos de la api, para ello lo primero he definido los end points, para que apunten hacia 
lo que queremos recuperar de la api. Despues he definido el modelo de la api, el cual incluye los mismos 
campos que la api y tambien he realizado el mapper para convertir nuestro modelo de api. Por ultimo he
definido la fuente de datos de remoto, la cual incluye el metodo que recupera nuestros desarrolladores. 
Por ultimo, he creado el repositorio para los datos de remoto.

Despues he incluido nuestra fuente de datos local, en este caso Room, aqui vamos a guardar los datos recuperados de remoto, 
estos de actulizaran con remoto cada 24 horas ya que se ha incluido una cache temporal. Para implementar Room,
creamos nuestra entidad, en este caso he declarado como clave primaria, el id que nos viene del modelo de api.
Despues he creado el dao, el cual incluye tres Querys, una que recupera, otra que borra y otra que
guarda. Despues incluimos nuestro mapper, en este caso el que devuelve el modelo de entidad recibe el parametro 
lastFetch por parametro donde vamos a almacenar la ultima vez que fue actualizado desde remoto. Tambien tendremos 
nuestra fuente de datos local, la cual contiene el metodo que nos va a recuperar los desarrolladores, y segun si
la lista que devuelve esta caducada o no, se devuelve una lista vacia y sino se devuelve la lista de desarrolladores
accediendo en ambos casos al right del Either, en el caso de esta sea nula devolvemos el lado izquierdo el cual 
contiene un AppError.

Tras haber realizado nuestra fuente remota y local, ahora en nuestro repositorio de data vamos a definir que
los datos se recojan de remoto y se guarden en local, de modo que aqui comprobamos, si el local esta vacio, si 
es asi recueperamos el remoto, borramos en local y guardamos en local, si no esta vacia, devolvemos el right del either,
este nos devuelve la lista de local.

Para terminar con data, solo nos faltaria incluir el dao y la entidad en la base de datos y ademas en nuestra 
carpeta de dagger, deberemos crear el module provides, el cual incluye un singleton donde recuperamos el dao
y tambien hay que incluir el singleton para retrofit, el cual crea una implementacion de la api. Por ultimo 
tenemos que crear nuestro modulo, en el cual vamos a bindear nuestros repositorios, tanto el local, como el remoto
ademas, tambien bindeamos nuestro data repository.

DOMAIN:

En domain solo tendremos nuestro modelo de dominio, el caso de uso que recupera los desarrolladores y nuestro repositorio 
de dominio.

PRESENTATION:

Aqui hemos de crear nuestro Adapter, ViewHolder e implementacion de diffutil, en el viewholder, bindemos 
nuestro dialog con los datos recibidos, para cargarlos en el recyclerview. 
Por ultimo necesitamos nuestro view model, el cual tiene un metodo encargado de cargar los datos, este view model
tiene 3 estados, isLoading para saber si esta cargando, error, donde devolveremos un error y developersList donde se alojara nuestra
lista de desarrolladores. Por ultimo nuestro fragmento principal, el cual no tiene nada de especial, salvo que en el setOnClickItem del
observer, he incluido una funcion la cual sera la encargada de parsear y redirigir a la url del link introducido por cada
desarrollador.
## VIDEO
[device-2023-02-09-234241.webm](https://user-images.githubusercontent.com/53609303/217955806-23e4f868-a860-4d06-ad8b-0ad59825ba11.webm)

2023-02-10 01:15 UTC, josem-perram requested changes
Please, revisa algunos comentarios de estilos, por lo demás está 🚀

2023-02-10 01:15 UTC, josem-perram commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:layout_width="100dp"
@OscarAntona acuérdate de usar siempre dimens. Puedes usar para el width y height el dimen: height_image_grid_card después renombraremos el naming que no es muy correcto.

2023-02-10 01:15 UTC, josem-perram commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:id="@+id/label_developer_name"
Hay que meterle un style: TitleCard

2023-02-10 01:15 UTC, josem-perram commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:id="@+id/label_developer_degree"
Hay que meterle un style: BodyCard

2023-02-10 01:15 UTC, josem-perram commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:tint="@color/md_theme_light_onPrimary"
Tenemos que usar estilos. Para la flecha no hace falta que sea un Shapeable, vale con un ImageView. No te preocupes por el color que se muestra. Se cambiará por estilos. Todos los estilos: tint, etc. no corresponden.

2023-02-10 01:15 UTC, josem-perram commented on app/src/main/res/layout/fragment_developers_dialog.xml
> +        android:scrollbars="none"
why??

2023-02-10 09:44 UTC, OscarAntona commented on app/src/main/res/layout/fragment_developers_dialog.xml
> +        android:scrollbars="none"
Pues la quite por que no quedaba muy bien la verdad, se metia casi encima del icono de la flecha y ademas no le veia mucho sentido ya que casi no llegamos a scrollear, al estirar el dialog se ven practicamente todos los desarrolladores ya, pero lo puedo quitar y ya le echaremos un ojo mas adelante, cuando nos centremos mas en el diseño

2023-02-10 09:45 UTC, OscarAntona commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:layout_width="100dp"
se me paso completamente

2023-02-10 09:45 UTC, OscarAntona commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:id="@+id/label_developer_name"
👍

2023-02-10 09:45 UTC, OscarAntona commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:id="@+id/label_developer_degree"
okay, lo añado

2023-02-10 09:46 UTC, OscarAntona commented on app/src/main/res/layout/developer_dialog_item.xml
> +            android:tint="@color/md_theme_light_onPrimary"
okay si, no hay problema, ya le daremos una vuelta a los estilos

2023-02-12 19:02 UTC, josem-perram approved these changes
Genial 🚀  Hago merge de la PR para intentar solucionar los errores de la CI.

2023-02-12 19:03 UTC, merged